### ISSUE TITLE
Add sample data

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/sumgram#14]
In the Usage section of the README there are links to a few Archive-It collections, but it might not be clear for users how that data was collected from those links. They might attempt to open those collection links in hope of downloading text.

I think, it will be helpful to include some sample files/folders with public domain data (such as books from the [Project Gutenberg](https://www.gutenberg.org/)) that can be used in illustration as well as tests.

**Comment by anwala** [comment]
[Sample data](https://github.com/oduwsdl/sumgram/tree/master/tests/unit/sample_cols) has been included as part of tests.
