### ISSUE TITLE
Incomplete results

### ISSUE THREAD

**Issue by anilozdemir96** [oduwsdl/sumgram#26]
Hello there,
First of all, thank you very much for your valuable work. Although I overwrite and change the min-df parameter, if the term_rate of the sumgrams found is lower than 0.01, it does not appear in the results. Do you have any ideas on this?

Thanks

**Comment by anwala** [comment]
Hello @anilozdemir96,

I'm glad you're finding some use with Sumgram. 

From your explanation,
>"Although I overwrite and change the min-df parameter, if the term_rate of the sumgrams found is lower than 0.01, it does not appear in the results."

It looks like sumgram is working as expected. According to explanation of [Performance Considerations - size of vocabulary (manipulating min_df)](https://github.com/oduwsdl/sumgram#performance-considerations---size-of-vocabulary-manipulating-min_df): 
> "terms with document frequencies less than min_df (DF < `min_df`) are removed"

I think you might have misunderstood the use of `min_df`. If Sumgram is removing too much from the vocabulary, it means `min_df` might be too high. So try to reduce it.

If you think I've misunderstood you. Please clarify and include the exact command line instructions you used.

I hope this helps.

**Comment by anilozdemir96** [comment]
Hello @anwala ,

Thank you very much for your quick response. Actually, I know how to use min-df, I don't think the problem is there. The problem is that although I decrease the min-df, the number of incoming outputs is not increasing. I did not use Sumgram over the command line, I installed it as pip install sumgram instead and called it with the function get_top_sumgrams on the jupyter notebook. The parameters I set were as follows.

params_new = {
    'top_sumgram_count': 100000,
    'add_stopwords': ['hanya'],
    'no_rank_sentences': False,
    'title': 'Top sumgrams for Hurricane Harvey text collection',
    'max-ngram': 10000,
    'min-df': 0.00001,
    'no-rank-docs': False,
    'pretty-print': True,
    'sentences-rank-count':1000,
    'sentence-tokenizer': 'regex',
    'no-parent-sentences' : True,
    'ngram-printing-mw': 40
}

After trying for a long time, I realized that the min_df variable in the **extract_top_ngrams** function is somehow updated to its default value of 0.01, so the "min-df" parameter that I set at the beginning is somehow overwrite. When I manually set the variable I mentioned in this function (in the source code), the problem I mentioned was fixed. But of course it's not a very effective solution. The problem may not be happening when sumgram is used directly from the command line. It may also be due to my misunderstanding.

Best,
Anıl

**Comment by anwala** [comment]
Hello again @anilozdemir96,

Thanks for the details. The reverting to the default `min_df` value even after you supplied a different value is not expected behavior suggesting a bug. I'm glad you were able to find a workaround, but I'd investigate this further and issue a patch if needed. Thanks!

**Comment by anwala** [comment]
@anilozdemir96,

Sorry it took so long to look into this. I realized the problem is not actually due to a bug. You misspelled `min_df` as `min-df`. So the function used the default value. All parameters use underscore not dash. I hope this helps.
