### ISSUE TITLE
Unable to install numpy 1.17.0 with setup script

### ISSUE THREAD

**Issue by jedmijares** [oduwsdl/sumgram#27]
I wasn't able to install sumgram with pip on my machine, until I cloned it locally and changed the setup script to install the latest version of numpy instead of 1.17.0.

For reference, I'm on Ubuntu and using Python 3.8.5.

**Comment by anwala** [comment]
Hello @jedmijares,

Thanks for reporting this. We will investigate this.

Respectfully,

Alex

**Comment by shawnmjones** [comment]
I just traced my Hypercane installation problems down to this. Remove the pinned version from setup.py (e.g., set `numpy==1.17.1` to just `numpy`). From reviewing https://github.com/oduwsdl/sumgram/blob/31434eaf21dfa3928f1b9e9b90c2f63e72416ed5/sumgram/sumgram.py#L1178-L1179 sumgram only needs the `sum` and `argwhere` functions. These shouldn't change between versions of numpy so there is no need to pin the version.

**Comment by anwala** [comment]
Hello @jedmijares  and @shawnmjones. This issue has been resolved in sumgram `v0.0.19`. Thank you.
