### ISSUE TITLE
doc_list is unexpectedly mutated in get_top_sumgrams()

### ISSUE THREAD

**Issue by immacdonald** [oduwsdl/sumgram#35]
The list of documents passed in for the get_top_sumgrams() function is unexpectedly modified such that it is not possible to repeatedly analyze the same set of documents (which is useful when comparing results with different ngram or param values). This doesn't appear to be clearly documented which can lead to unintuitive behaviour occuring. An easy solution to this would be to just perform a deep copy on the docs list upon it being passed in, and then modifying that copy instead for the purposes of the function.

**Comment by anwala** [comment]
This issues has been [addressed from v1.0.4](https://github.com/oduwsdl/sumgram/commit/d43a5c5249267fcbdf161e7cee055e134f2afc21)
