### ISSUE TITLE
Separate output from processing in get_top_ngrams

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/sumgram#5]
As a library user, if I want to call get_top_ngrams but want to further process the output myself, I have to content with all of this print output that I will never use. This print output also clogs up a potentially already messy screen for my program's users.

My suggestion:
* store the output of get_top_ngrams into some kind of data structure and remove the existing print statements
* create a separate function that a program can call in order to print it out if needed

**Comment by anwala** [comment]
Thanks for the suggestion. I've implemented the following changes (See logfixes branch: https://github.com/oduwsdl/sumgram/tree/logfixes): 

- when the script is invoked from a python script, it is silent by default.
- when used from the command line, it is verbose by default (print output is controlled by setting the log level - info, error, notset, etc.)
